apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: purchase-order-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-order-service
spec:
  selector:
    matchLabels:
      app: purchase-order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: purchase-order-service
    spec:
      containers:
        - name: purchase-order-service
          image: purchase-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3010
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: PORT_PURCHASE_ORDER_SERVICE
          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: microservices-secrets
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: purchase-order-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-order-service
spec:
  selector:
    app: purchase-order-service
  ports:
    - port: 3010
      targetPort: 3010
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: purchase-order-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: purchase-order-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
