apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
type: Opaque
stringData:
  # Database
  MONGODB_URI: "mongodb+srv://beichtuan:_ZSZjQDyRaA_hq8@grocerystoremanagement.0kkdf.mongodb.net/data?retryWrites=true&w=majority"

  # JWT
  ACCESS_TOKEN: "access_token"

  # Cloudinary
  CLOUDINARY_API_KEY: "143368966583968"
  CLOUDINARY_API_SECRET: "TRCLlK0PNzde_hUvq6kc_8j198w"

  # MOMO
  MOMO_ACCESS_KEY: "F8BBA842ECF85"
  MOMO_SECRET_KEY: "K951B6PE1waDMi640xX08PD3vg6EkVlz"
  MOMO_API_ENDPOINT: "https://test-payment.momo.vn/v2/gateway/api"
  MOMO_REDIRECT_URL: "http://localhost:3000/callback"
  MOMO_IPN_URL: "http://localhost:3000/callback"

  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "user"
  RABBITMQ_PASSWORD: "password"
